### ISSUE TITLE
Need an example.

### ISSUE THREAD

**Issue by NeishaS** [alancting/react-cas-client#4]
Hi! Thank you for sharing your library.
I am new to React and CAS.
I am trying to add authentication to my react app using CAS for my organization.
Could you share an example on how and when to call the CASclient for user authentication?
I called the casClient on a button click, but it adds service of localhost in the query param, is there a way to pass in the service URL? or do i need to register mylocalhost port with cas for development and testing?
I am not sure how will I fetch or receive the ticket to validate the user and how to go forward after that.
Would you please share an example of how to use this library, will really appreciate it.

**Comment by NeishaS** [comment]
Never mind, got it working. 
Once again, thank you so much for sharing this library. :)

**Comment by alancting** [comment]
@NeishaS sorry my bad, I didn't noticed any notification...

Normally, your cas server would allow *.domain.com, so for development, I would add `127.0.0.1 local.domain.com` to `/etc/hosts`, and use the URL `local.domain.com:5000` instead of `loclahost:5000`
