### ISSUE TITLE
Validation proxy could be from other domain

### ISSUE THREAD

**Issue by FrederickFarfan** [alancting/react-cas-client#6]
Hi there! Nice work!

Just one thing:
CAS options should have a "validation_proxy_domain" because the service ticket could be validated in an API from other server, and its value should be "window.location.origin" by default.

Then, in urls.js (line 108):
`return cas.validation_proxy_domain + cas.validation_proxy_path + cas.path;`

**Comment by alancting** [comment]
Hi there, 

Sorry for the late reply, finally got some free time to follow up on this project.
Thank you for the suggestion, I've updated the lib.

Many thanks 👍 💯
