### ISSUE TITLE
Demo Program

### ISSUE THREAD

**Issue by syamasundararao** [alancting/react-cas-client#7]
If possible can you add demo program

**Comment by Mathewsmusukuma** [comment]
@alancting, do you have a demo app for this to share as an example?

**Comment by alancting** [comment]
Hi all, apologize for the late response.
I'm now working on this right now. Hopefully i can make it by this weekend. 🙏

**Comment by Mathewsmusukuma** [comment]
Thank you very much, really appreciate! 🙏

**Comment by alancting** [comment]
HI all, please find the example at [alancting/react-cas-client-example](https://github.com/alancting/react-cas-client-example). Cheers!
